# https://snyk.io/blog/github-actions-to-securely-publish-npm-packages/
# https://docs.github.com/en/actions/guides/publishing-nodejs-packages

name: Release

on:

  # Trigger if there's a tagged (e.g. tag v1.0.0) commit pushed to master:
  push:
    tags:
      - v*

jobs:

  publish:
    runs-on: ubuntu-20.04

    # Set the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Build & Test
        run: |
          pnpm i --frozen-lockfile
          pnpm test

      # Set the target repository and NPM authentication token manually instead of through actions/setup-node.
      # Publishes to NPM using the "ignore scripts" flag to skip all the life cycle scripts specified in the packge.json manifest.
      # Doing this through PNPM with the same flag causes ESBuild to crash.
      - name: Publish to NPM
        run: |
          pnpm config set registry https://registry.npmjs.org/
          pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # https://www.aaron-powell.com/posts/2020-11-06-deploy-to-github-packages-with-github-actions/
      #
      # Same as the NPM publishing, but this time targeting the GitHub packages repository.
      # Could require a scope, but should default to "tropicalraisel."
      - name: Publish to GitHub Packages
        run: |
          pnpm config set registry https://npm.pkg.github.com/
          pnpm config set //npm.pkg.github.com/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: publish
    runs-on: ubuntu-20.04

    steps:
      - name: Publish GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
