name: Test

on:
  push:
    branches:
      - master
    paths:
      - '**.ts'
      - '.github/workflows/test.yml'

  pull_request:
    branches:
      - master
    paths:
      - '**.ts'
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, macos-latest]
      # fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Test
        run: pnpm test
        env:
          CI: true
